# Generated by Django 4.1.3 on 2023-04-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='ContactMessage',
        ),
    ]
