# Generated by Django 4.2 on 2023-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_user_user_id_remove_profile_reset_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
