# Generated by Django 4.2.2 on 2023-06-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profile_reset_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.CreateModel(
            name='engineerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=25)),
                ('cnic', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=50)),
                ('degreeType', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('passOut', models.DateField()),
                ('pecNo', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
            options={
                'db_table': 'engineerDetails',
                'ordering': ['firstname'],
            },
        ),
    ]
