# Generated by Django 4.2.2 on 2023-06-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_profile_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userProfile',
        ),
    ]
