# Generated by Django 4.2 on 2023-07-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_engineerdetails_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=25)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.userprofile')),
            ],
            options={
                'db_table': 'userDetails',
                'ordering': ['firstname'],
            },
        ),
    ]
