# Generated by Django 4.2.2 on 2023-07-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userr',
        ),
    ]
